In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [4]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [5]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [7]:
unique_emotions= df['emotion'].unique()
emotion_numbers={}
i=0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i+=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [8]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [9]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [10]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [11]:
df['text'] = df['text'].apply(remove_punc)

In [12]:
def remove_nums(txt):
  new= ""
  for i in txt:
    if not i.isdigit():
      new+=i
  return new
df['text'] = df['text'].apply(remove_nums)

In [13]:
import re

def remove_urls(txt):
    txt = re.sub(r'http\S+', '', txt)      # Removes http:// and https:// URLs
    txt = re.sub(r'www\.\S+', '', txt)     # Removes www URLs
    return txt

df['text'] = df['text'].apply(remove_urls)

In [14]:
#Emoji remove

def remove_emoji(txt):
    new = ""
    for i in txt:
      if i.isascii():
        new+=i
    return new

df['text'] = df['text'].apply(remove_emoji)

In [15]:
# Remove StopWords

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
nltk.download('punkt')

stop_words = set(stopwords.words('english'))
stop_words

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [16]:
def remove(txt): #remove the stop words
  words = txt.split()
  cleaned=[]
  for i in words:
    if i not in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [17]:
df['text'] = df['text'].apply(remove)

In [18]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [19]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [20]:
df.shape

(16000, 2)

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['text'],
    df['emotion'],
    test_size=0.20,
    random_state=42
)

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

In [23]:
bow_vectorizer = CountVectorizer()
bow_vectorizer.fit(X_train)

CountVectorizer()

In [24]:
x_train_bow = bow_vectorizer.transform(X_train)
x_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116052 stored elements and shape (12800, 13360)>

In [25]:
x_test_bow = bow_vectorizer.transform(X_test)
x_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26936 stored elements and shape (3200, 13360)>

In [26]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score


nb_model = MultinomialNB()
nb_model.fit(x_train_bow, y_train)


pred_bow = nb_model.predict(x_test_bow)
print(accuracy_score(y_test, pred_bow))

0.768125

In [27]:
tfidf_vectorizer = TfidfVectorizer() # using tfidf
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [28]:
nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [29]:
y_pred = nb2_model.predict(X_test_tfidf)


print(accuracy_score(y_test, y_pred))

0.6609375

In [30]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(max_iter=1000)


logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [31]:
log_pred = logistic_model.predict(X_test_tfidf)
print(accuracy_score(y_test,log_pred ))

0.8615625

In [32]:
import pickle

# Save Logistic Regression Model
with open("logistic_model.pkl","wb") as file:
    pickle.dump(logistic_model,file)

# Save TF-IDF Vectorizer
with open("tfidf_vectorizer.pkl","wb") as file:
    pickle.dump(tfidf_vectorizer,file)

print("Files Saved Successfully")

Files Saved Successfully

In [34]:
import pickle

pickle.dump(emotion_numbers, open("emotion_mapping.pkl", "wb"))

In [33]:
pickle.dump(logistic_model, open("logistic_model.pkl", "wb"))
pickle.dump(tfidf_vectorizer, open("tfidf_vectorizer.pkl", "wb"))
pickle.dump(emotion_numbers, open("emotion_mapping.pkl", "wb"))

In [38]:
print(emotion_numbers)

print(df['emotion'].unique())

print(logistic_model.classes_)

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}
[0 1 2 3 4 5]
[0 1 2 3 4 5]